language: go
go:
  - 1.9

script:
  - find . -name "package.json" -execdir npm install \;
  - curl -sL https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 > dep
  - chmod +x ./dep
  - ./dep ensure
  - make install.deps
  - make test.ci
